name: Excluir branch BIB após merge no master

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  delete_merged_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verificar se a PR foi mesclada e deletar branch BIB
        if: github.event.pull_request.merged == true
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "PR foi mesclada. Branch de origem: $BRANCH_NAME"
          if [[ "${{ github.event.pull_request.base.ref }}" == "master" ]]; then
            if [[ "$BRANCH_NAME" == BIB-* ]]; then
              echo "Branch $BRANCH_NAME é do tipo BIB. Deletando..."
              git push origin --delete "$BRANCH_NAME"
            else
              echo "Branch $BRANCH_NAME não é do tipo BIB. Não será deletada."
            fi
          else
            echo "Merge não foi na branch master. Não deletando a branch."
          fi
